//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nop.Plugin.Shipping.Gls.GlsWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gls.dk/webservices/", ConfigurationName="GlsWebService.wsShopFinderSoap")]
    public interface wsShopFinderSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gls.dk/webservices/GetOneParcelShop", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Nop.Plugin.Shipping.Gls.GlsWebService.PakkeshopData GetOneParcelShop(string ParcelShopNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gls.dk/webservices/GetOneParcelShop", ReplyAction="*")]
        System.Threading.Tasks.Task<Nop.Plugin.Shipping.Gls.GlsWebService.PakkeshopData> GetOneParcelShopAsync(string ParcelShopNumber);
        
        // CODEGEN: Parameter 'GetAllParcelShopsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://gls.dk/webservices/GetAllParcelShops", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Nop.Plugin.Shipping.Gls.GlsWebService.GetAllParcelShopsResponse GetAllParcelShops(Nop.Plugin.Shipping.Gls.GlsWebService.GetAllParcelShopsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gls.dk/webservices/GetAllParcelShops", ReplyAction="*")]
        System.Threading.Tasks.Task<Nop.Plugin.Shipping.Gls.GlsWebService.GetAllParcelShopsResponse> GetAllParcelShopsAsync(Nop.Plugin.Shipping.Gls.GlsWebService.GetAllParcelShopsRequest request);
        
        // CODEGEN: Parameter 'GetParcelShopsInZipcodeResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://gls.dk/webservices/GetParcelShopsInZipcode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Nop.Plugin.Shipping.Gls.GlsWebService.GetParcelShopsInZipcodeResponse GetParcelShopsInZipcode(Nop.Plugin.Shipping.Gls.GlsWebService.GetParcelShopsInZipcodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gls.dk/webservices/GetParcelShopsInZipcode", ReplyAction="*")]
        System.Threading.Tasks.Task<Nop.Plugin.Shipping.Gls.GlsWebService.GetParcelShopsInZipcodeResponse> GetParcelShopsInZipcodeAsync(Nop.Plugin.Shipping.Gls.GlsWebService.GetParcelShopsInZipcodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gls.dk/webservices/SearchNearestParcelShops", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Nop.Plugin.Shipping.Gls.GlsWebService.ParcelShopSearchResult SearchNearestParcelShops(string street, string zipcode, string countryIso3166A2, int Amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gls.dk/webservices/SearchNearestParcelShops", ReplyAction="*")]
        System.Threading.Tasks.Task<Nop.Plugin.Shipping.Gls.GlsWebService.ParcelShopSearchResult> SearchNearestParcelShopsAsync(string street, string zipcode, string countryIso3166A2, int Amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gls.dk/webservices/GetParcelShopDropPoint", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Nop.Plugin.Shipping.Gls.GlsWebService.ParcelShopSearchResult GetParcelShopDropPoint(string street, string zipcode, string countryIso3166A2, int Amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gls.dk/webservices/GetParcelShopDropPoint", ReplyAction="*")]
        System.Threading.Tasks.Task<Nop.Plugin.Shipping.Gls.GlsWebService.ParcelShopSearchResult> GetParcelShopDropPointAsync(string street, string zipcode, string countryIso3166A2, int Amount);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gls.dk/webservices/")]
    public partial class PakkeshopData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numberField;
        
        private string companyNameField;
        
        private string streetnameField;
        
        private string streetname2Field;
        
        private string zipCodeField;
        
        private string cityNameField;
        
        private string countryCodeField;
        
        private string countryCodeISO3166A2Field;
        
        private string telephoneField;
        
        private string longitudeField;
        
        private string latitudeField;
        
        private int distanceMetersAsTheCrowFliesField;
        
        private Weekday[] openingHoursField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
                this.RaisePropertyChanged("CompanyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Streetname {
            get {
                return this.streetnameField;
            }
            set {
                this.streetnameField = value;
                this.RaisePropertyChanged("Streetname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Streetname2 {
            get {
                return this.streetname2Field;
            }
            set {
                this.streetname2Field = value;
                this.RaisePropertyChanged("Streetname2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("ZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
                this.RaisePropertyChanged("CityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("CountryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CountryCodeISO3166A2 {
            get {
                return this.countryCodeISO3166A2Field;
            }
            set {
                this.countryCodeISO3166A2Field = value;
                this.RaisePropertyChanged("CountryCodeISO3166A2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Telephone {
            get {
                return this.telephoneField;
            }
            set {
                this.telephoneField = value;
                this.RaisePropertyChanged("Telephone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int DistanceMetersAsTheCrowFlies {
            get {
                return this.distanceMetersAsTheCrowFliesField;
            }
            set {
                this.distanceMetersAsTheCrowFliesField = value;
                this.RaisePropertyChanged("DistanceMetersAsTheCrowFlies");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Weekday[] OpeningHours {
            get {
                return this.openingHoursField;
            }
            set {
                this.openingHoursField = value;
                this.RaisePropertyChanged("OpeningHours");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gls.dk/webservices/")]
    public partial class Weekday : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Day dayField;
        
        private Hour openAtField;
        
        private Break[] breaksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Day day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
                this.RaisePropertyChanged("day");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Hour openAt {
            get {
                return this.openAtField;
            }
            set {
                this.openAtField = value;
                this.RaisePropertyChanged("openAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Break[] breaks {
            get {
                return this.breaksField;
            }
            set {
                this.breaksField = value;
                this.RaisePropertyChanged("breaks");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gls.dk/webservices/")]
    public enum Day {
        
        /// <remarks/>
        Monday,
        
        /// <remarks/>
        Tuesday,
        
        /// <remarks/>
        Wednesday,
        
        /// <remarks/>
        Thursday,
        
        /// <remarks/>
        Friday,
        
        /// <remarks/>
        Saturday,
        
        /// <remarks/>
        Sunday,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gls.dk/webservices/")]
    public partial class Hour : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fromField;
        
        private string toField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
                this.RaisePropertyChanged("From");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
                this.RaisePropertyChanged("To");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gls.dk/webservices/")]
    public partial class ParcelShopSearchResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AccuracyLevel accuracylevelField;
        
        private PakkeshopData[] parcelshopsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AccuracyLevel accuracylevel {
            get {
                return this.accuracylevelField;
            }
            set {
                this.accuracylevelField = value;
                this.RaisePropertyChanged("accuracylevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PakkeshopData[] parcelshops {
            get {
                return this.parcelshopsField;
            }
            set {
                this.parcelshopsField = value;
                this.RaisePropertyChanged("parcelshops");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gls.dk/webservices/")]
    public enum AccuracyLevel {
        
        /// <remarks/>
        EXACT,
        
        /// <remarks/>
        STREET,
        
        /// <remarks/>
        ZIP,
        
        /// <remarks/>
        UNKNOWN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gls.dk/webservices/")]
    public partial class Break : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string startField;
        
        private string endField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("Start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
                this.RaisePropertyChanged("End");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllParcelShops", WrapperNamespace="http://gls.dk/webservices/", IsWrapped=true)]
    public partial class GetAllParcelShopsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gls.dk/webservices/", Order=0)]
        public string countryIso3166A2;
        
        public GetAllParcelShopsRequest() {
        }
        
        public GetAllParcelShopsRequest(string countryIso3166A2) {
            this.countryIso3166A2 = countryIso3166A2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllParcelShopsResponse", WrapperNamespace="http://gls.dk/webservices/", IsWrapped=true)]
    public partial class GetAllParcelShopsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gls.dk/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Nop.Plugin.Shipping.Gls.GlsWebService.PakkeshopData[] GetAllParcelShopsResult;
        
        public GetAllParcelShopsResponse() {
        }
        
        public GetAllParcelShopsResponse(Nop.Plugin.Shipping.Gls.GlsWebService.PakkeshopData[] GetAllParcelShopsResult) {
            this.GetAllParcelShopsResult = GetAllParcelShopsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetParcelShopsInZipcode", WrapperNamespace="http://gls.dk/webservices/", IsWrapped=true)]
    public partial class GetParcelShopsInZipcodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gls.dk/webservices/", Order=0)]
        public string zipcode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gls.dk/webservices/", Order=1)]
        public string countryIso3166A2;
        
        public GetParcelShopsInZipcodeRequest() {
        }
        
        public GetParcelShopsInZipcodeRequest(string zipcode, string countryIso3166A2) {
            this.zipcode = zipcode;
            this.countryIso3166A2 = countryIso3166A2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetParcelShopsInZipcodeResponse", WrapperNamespace="http://gls.dk/webservices/", IsWrapped=true)]
    public partial class GetParcelShopsInZipcodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gls.dk/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Nop.Plugin.Shipping.Gls.GlsWebService.PakkeshopData[] GetParcelShopsInZipcodeResult;
        
        public GetParcelShopsInZipcodeResponse() {
        }
        
        public GetParcelShopsInZipcodeResponse(Nop.Plugin.Shipping.Gls.GlsWebService.PakkeshopData[] GetParcelShopsInZipcodeResult) {
            this.GetParcelShopsInZipcodeResult = GetParcelShopsInZipcodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsShopFinderSoapChannel : Nop.Plugin.Shipping.Gls.GlsWebService.wsShopFinderSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsShopFinderSoapClient : System.ServiceModel.ClientBase<Nop.Plugin.Shipping.Gls.GlsWebService.wsShopFinderSoap>, Nop.Plugin.Shipping.Gls.GlsWebService.wsShopFinderSoap {
        
        public wsShopFinderSoapClient() {
        }
        
        public wsShopFinderSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsShopFinderSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsShopFinderSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsShopFinderSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Nop.Plugin.Shipping.Gls.GlsWebService.PakkeshopData GetOneParcelShop(string ParcelShopNumber) {
            return base.Channel.GetOneParcelShop(ParcelShopNumber);
        }
        
        public System.Threading.Tasks.Task<Nop.Plugin.Shipping.Gls.GlsWebService.PakkeshopData> GetOneParcelShopAsync(string ParcelShopNumber) {
            return base.Channel.GetOneParcelShopAsync(ParcelShopNumber);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nop.Plugin.Shipping.Gls.GlsWebService.GetAllParcelShopsResponse Nop.Plugin.Shipping.Gls.GlsWebService.wsShopFinderSoap.GetAllParcelShops(Nop.Plugin.Shipping.Gls.GlsWebService.GetAllParcelShopsRequest request) {
            return base.Channel.GetAllParcelShops(request);
        }
        
        public Nop.Plugin.Shipping.Gls.GlsWebService.PakkeshopData[] GetAllParcelShops(string countryIso3166A2) {
            Nop.Plugin.Shipping.Gls.GlsWebService.GetAllParcelShopsRequest inValue = new Nop.Plugin.Shipping.Gls.GlsWebService.GetAllParcelShopsRequest();
            inValue.countryIso3166A2 = countryIso3166A2;
            Nop.Plugin.Shipping.Gls.GlsWebService.GetAllParcelShopsResponse retVal = ((Nop.Plugin.Shipping.Gls.GlsWebService.wsShopFinderSoap)(this)).GetAllParcelShops(inValue);
            return retVal.GetAllParcelShopsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Nop.Plugin.Shipping.Gls.GlsWebService.GetAllParcelShopsResponse> Nop.Plugin.Shipping.Gls.GlsWebService.wsShopFinderSoap.GetAllParcelShopsAsync(Nop.Plugin.Shipping.Gls.GlsWebService.GetAllParcelShopsRequest request) {
            return base.Channel.GetAllParcelShopsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Nop.Plugin.Shipping.Gls.GlsWebService.GetAllParcelShopsResponse> GetAllParcelShopsAsync(string countryIso3166A2) {
            Nop.Plugin.Shipping.Gls.GlsWebService.GetAllParcelShopsRequest inValue = new Nop.Plugin.Shipping.Gls.GlsWebService.GetAllParcelShopsRequest();
            inValue.countryIso3166A2 = countryIso3166A2;
            return ((Nop.Plugin.Shipping.Gls.GlsWebService.wsShopFinderSoap)(this)).GetAllParcelShopsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nop.Plugin.Shipping.Gls.GlsWebService.GetParcelShopsInZipcodeResponse Nop.Plugin.Shipping.Gls.GlsWebService.wsShopFinderSoap.GetParcelShopsInZipcode(Nop.Plugin.Shipping.Gls.GlsWebService.GetParcelShopsInZipcodeRequest request) {
            return base.Channel.GetParcelShopsInZipcode(request);
        }
        
        public Nop.Plugin.Shipping.Gls.GlsWebService.PakkeshopData[] GetParcelShopsInZipcode(string zipcode, string countryIso3166A2) {
            Nop.Plugin.Shipping.Gls.GlsWebService.GetParcelShopsInZipcodeRequest inValue = new Nop.Plugin.Shipping.Gls.GlsWebService.GetParcelShopsInZipcodeRequest();
            inValue.zipcode = zipcode;
            inValue.countryIso3166A2 = countryIso3166A2;
            Nop.Plugin.Shipping.Gls.GlsWebService.GetParcelShopsInZipcodeResponse retVal = ((Nop.Plugin.Shipping.Gls.GlsWebService.wsShopFinderSoap)(this)).GetParcelShopsInZipcode(inValue);
            return retVal.GetParcelShopsInZipcodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Nop.Plugin.Shipping.Gls.GlsWebService.GetParcelShopsInZipcodeResponse> Nop.Plugin.Shipping.Gls.GlsWebService.wsShopFinderSoap.GetParcelShopsInZipcodeAsync(Nop.Plugin.Shipping.Gls.GlsWebService.GetParcelShopsInZipcodeRequest request) {
            return base.Channel.GetParcelShopsInZipcodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Nop.Plugin.Shipping.Gls.GlsWebService.GetParcelShopsInZipcodeResponse> GetParcelShopsInZipcodeAsync(string zipcode, string countryIso3166A2) {
            Nop.Plugin.Shipping.Gls.GlsWebService.GetParcelShopsInZipcodeRequest inValue = new Nop.Plugin.Shipping.Gls.GlsWebService.GetParcelShopsInZipcodeRequest();
            inValue.zipcode = zipcode;
            inValue.countryIso3166A2 = countryIso3166A2;
            return ((Nop.Plugin.Shipping.Gls.GlsWebService.wsShopFinderSoap)(this)).GetParcelShopsInZipcodeAsync(inValue);
        }
        
        public Nop.Plugin.Shipping.Gls.GlsWebService.ParcelShopSearchResult SearchNearestParcelShops(string street, string zipcode, string countryIso3166A2, int Amount) {
            return base.Channel.SearchNearestParcelShops(street, zipcode, countryIso3166A2, Amount);
        }
        
        public System.Threading.Tasks.Task<Nop.Plugin.Shipping.Gls.GlsWebService.ParcelShopSearchResult> SearchNearestParcelShopsAsync(string street, string zipcode, string countryIso3166A2, int Amount) {
            return base.Channel.SearchNearestParcelShopsAsync(street, zipcode, countryIso3166A2, Amount);
        }
        
        public Nop.Plugin.Shipping.Gls.GlsWebService.ParcelShopSearchResult GetParcelShopDropPoint(string street, string zipcode, string countryIso3166A2, int Amount) {
            return base.Channel.GetParcelShopDropPoint(street, zipcode, countryIso3166A2, Amount);
        }
        
        public System.Threading.Tasks.Task<Nop.Plugin.Shipping.Gls.GlsWebService.ParcelShopSearchResult> GetParcelShopDropPointAsync(string street, string zipcode, string countryIso3166A2, int Amount) {
            return base.Channel.GetParcelShopDropPointAsync(street, zipcode, countryIso3166A2, Amount);
        }
    }
}
